### PR TITLE
Fix for ar-consumer. AVRO for consumer.

### PR DESCRIPTION
**Pull request by lgjenero**

### CODE REVIEW

**Comment by pkoro** [comment]
Luko, can you update also version/release numbers and changelog in spec file so that we deploy the change once pulled?

**Comment by lgjenero** [comment]
Yes will do. Adding a fix for a bug I just found

**Comment by lgjenero** [comment]
@pkoro rasied version number and added fix.

**Comment by lgjenero** [comment]
@pkoro Done.

**Pull request merged**
